language: python
python:
  - "2.7"

install:
  - pip install flake8
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE=coursereviews.settings.testing

script:
  - flake8
  - python manage.py test reviews stats
